version: "3.9"
services:
  flask:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:7
    ports:
      - 6379:6379